# Generated by Django 2.1.1 on 2018-10-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbapi', '0003_auto_20181006_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='isAdult',
            field=models.BooleanField(choices=[('0', False), ('1', True)], default=False, help_text='False: non-adult title; True: adult title'),
        ),
    ]
