# Generated by Django 2.1.1 on 2018-10-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbapi', '0004_auto_20181006_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ('primaryTitle',)},
        ),
        migrations.AlterField(
            model_name='titles',
            name='originalTitle',
            field=models.CharField(default='', help_text='Original title, in the original language', max_length=1000),
        ),
        migrations.AlterField(
            model_name='titles',
            name='primaryTitle',
            field=models.CharField(default='', help_text='The more popular title / the title used by the filmmakers on promotional materials at the point of release', max_length=1000),
        ),
    ]
