# Generated by Django 2.1 on 2018-08-14 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2048)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
                ('year', models.CharField(default='N/A', max_length=10)),
                ('rated', models.CharField(default='N/A', max_length=50)),
                ('released', models.CharField(default='N/A', max_length=50)),
                ('runtime', models.CharField(default='N/A', max_length=50, verbose_name='runtime in minutes')),
                ('genre', models.CharField(default='N/A', max_length=50)),
                ('director', models.CharField(default='N/A', max_length=50)),
                ('writer', models.CharField(default='N/A', max_length=100)),
                ('actors', models.CharField(default='N/A', max_length=1000)),
                ('plot', models.CharField(default='N/A', max_length=1000)),
                ('language', models.CharField(default='N/A', max_length=50)),
                ('country', models.CharField(default='N/A', max_length=50)),
                ('awards', models.CharField(default='N/A', max_length=100)),
                ('poster', models.CharField(default='N/A', max_length=200)),
                ('metascore', models.CharField(default='N/A', max_length=50)),
                ('imdbrating', models.FloatField(default=0, verbose_name='imdb rating')),
                ('imdbvotes', models.FloatField(default=0, verbose_name='imdb votes')),
                ('type', models.CharField(default='N/A', max_length=50)),
                ('totalseasons', models.CharField(default='N/A', max_length=10, verbose_name='total seasons')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='N/A', max_length=200)),
                ('value', models.FloatField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesrestapi.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesrestapi.Movie'),
        ),
    ]
