# Generated by Django 2.1 on 2018-08-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesrestapi', '0002_comment_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
