# Generated by Django 2.1 on 2018-08-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesrestapi', '0003_auto_20180811_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='totalseasons',
            field=models.CharField(default='N/A', max_length=10, verbose_name='total seasons'),
        ),
    ]
