# Generated by Django 2.1 on 2018-08-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omdbapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbrating',
            field=models.CharField(default='N/A', max_length=10, verbose_name='imdb rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbvotes',
            field=models.CharField(default='N/A', max_length=10, verbose_name='imdb votes'),
        ),
    ]
