# Generated by Django 2.1 on 2018-08-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omdbapi', '0003_auto_20180826_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
