# Generated by Django 2.1.1 on 2018-09-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omdbapi', '0004_auto_20180826_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='awards',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=models.CharField(default='N/A', max_length=1000),
        ),
    ]
